[package]
name = "guild_simulator"
version = "0.1.0"
edition = "2021"
authors = ["Guillaume Jolibois <jolibois.contact@gmail.com>"]
build-windows = ["./scripts/build-windows.sh"]

[build]
# Point to our `index.html`.
target = "web/index.html"
# Set the output directory for the web build.
dist = "target/trunk"
# This is needed in order to host the game on itch.io.
public_url = "./"

# ![feature(diagnostic_namespace)]

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

[target.x86_64h-apple-darwin]
# Add any specific settings you want here

# The default profile is optimized for Wasm builds because
# that's what [Trunk reads](https://github.com/trunk-rs/trunk/issues/605).
# Optimize for size in the wasm-release profile to reduce load times and bandwidth usage on web.
[profile.release]
# Compile the entire crate as one unit.
# Slows compile times, marginal improvements.
codegen-units = 1
# Do a second optimization pass over the entire program, including dependencies.
# Slows compile times, marginal improvements.
lto = "thin"
# Optimize with size in mind (also try "z", sometimes it is better).
# Slightly slows compile times, great improvements to file size and runtime performance.
opt-level = "s"
# Strip all debugging information from the binary to slightly reduce file size.
strip = "debuginfo"

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3

# Remove expensive debug assertions due to <https://github.com/bevyengine/bevy/issues/14291>
[profile.dev.package.wgpu-types]
debug-assertions = false

# Override some settings for native builds.
[profile.release-native]
# Default to release profile values.
inherits = "release"
# Optimize with performance in mind.
opt-level = 3
# Keep debug information in the binary.
strip = "none"


# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
# [profile.dev.package."*"]
# opt-level = 3

[dependencies]
bevy = { version = "0.14.0" }
# bevy-inspector-egui  = { git = "https://github.com/jakobhellermann/bevy-inspector-egui", tag = "v0.25.0" }
bevy_asset_loader = { version = "0.21.0", features = ["2d"]}
bevy-settings = "0.6.0"
rand_core = "0.6.4"
uuid = "1.10.0"
rand = "0.8.4"
ron = "0.8"
serde = { version = "1.0", features = ["derive"] }
pyri_tooltip = "0.1.1"
bevy_ui_mod_alerts = "0.2.0"
