[package]
name = "guild_simulator"
version = "0.1.0"
edition = "2021"

# ![feature(diagnostic_namespace)]

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
# [profile.dev.package."*"]
# opt-level = 3

[dependencies]
bevy = { version = "0.14.0", features = ["dynamic_linking"] }
bevy-inspector-egui  = { git = "https://github.com/jakobhellermann/bevy-inspector-egui", tag = "v0.25.0" }
bevy-settings = "0.6.0"
bevy_editor_pls = "0.8.1"
rand_core = "0.6.4"
uuid = "1.10.0"
